name: continuous-integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up Python
        uses: actions/setup-python@v2  # This assumes you are using an action to set up Python
      

        
  test:
    runs-on: ubuntu-latest
    needs: run

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Unit Tests
        run: |
          ls 
    
  run:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name : checkout 
        uses : actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python for the run job
      
      - name: Run App
        run: |
          ls 
         
