name: continuous-integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # This assumes you are using an action to set up Python
      

        
  
  test:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python again for the test job
      
     
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s . -p "test_app.py"  # Run tests
    
  run:
    runs-on: ubuntu-latest
    needs: test
      
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python for the run job
      
      - name: Run App
        run: |
          python "app.py"  # Run your application
